/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (52.81%)
 * Total Accepted:    138.2K
 * Total Submissions: 261.6K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
#include <string>

using namespace std;

class Solution {
  public:
    char findTheDifference(string s, string t) {
        int ans = 0;
        for (char &c : s) ans ^= c;
        for (char &c : t) ans ^= c;
        return static_cast<char>(ans);
    }
};

